CREATE OR REPLACE FUNCTION DISTANCE(L real[], R real[], N int) RETURNS real AS $$
DECLARE
  s real;
BEGIN
  s := 0;
  FOR i IN 1..n LOOP
    s := s + power((l[i] - r[i]), 2);
  END LOOP;
  RETURN sqrt(s);
END;
$$ LANGUAGE PLPGSQL;


CREATE TABLE PIVOTES(
	ID SERIAL,
	NAME VARCHAR,
	PRIMARY KEY (ID));

CREATE TABLE NODES(
	ID SERIAL, 
	PARENTID SMALLINT NULL,
	DISTANCE real, 
	PIVOTEID SMALLINT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (PARENTID) REFERENCES NODES(ID),
	FOREIGN KEY (PIVOTEID) REFERENCES PIVOTES(ID));

CREATE TABLE IMAGES(
	ID SERIAL, 
	NAME VARCHAR, 
	NODEID SMALLINT, 
	HISTOGRAM real[], 
	PRIMARY KEY (ID),
	FOREIGN KEY (NODEID) REFERENCES NODES(ID));